BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');


INSERT INTO plants (plant_name, scientific_name, plant_type, plant_image_1, plant_image_2, plant_image_3, plant_zone, water_level, light_level,difficulty_level, plant_description, plant_care) VALUES ('Cherry Tomato', 'Solanum lycopersicum var. cerasiforme', 'Vegetable', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733240001/CherryTomatoes_h4vrat_utuehj.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733240002/cherrytomatoes2_kkepr9_rozerf.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733240003/cherrytomatoes3_wg9dlv_t4y5dw.jpg', '2-11', '1-2', '3','2','Cherry tomatoes are small, bite-sized fruits that come in over 100 varieties. They tend to be about 2.5 centimeters wide, though they can vary in size. Cherry tomatoes can be red, yellow, orange, green, or dark purple.', 'Most cherry tomatoes are indeterminate and have a large, sprawling growth habit that requires pruning and support. When space is limited, many gardeners choose determinate varieties as they grow in a more compact, bush-like shape. Regardless of the variety, you should keep in mind that most tomatoes can benefit from staking or using a tomato cage to help keep fruit off the ground.');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_image_1, plant_image_2, plant_image_3, plant_zone, water_level, light_level,difficulty_level, plant_description, plant_care) VALUES ('Cucumber', 'Cucumis sativus', 'Vegetable', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239994/ARS_cucumber_fbic0b_vcwe6s.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241112/cucumber2_zpbz5d_lkt1fw.webp', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241099/How-to-Grow-Cucumber_etab9b_lgyplt.jpg', '4-11','1-2', '3','2','The cucumber is a member of the Cucurbitaceae family, and belongs to the same family as squash and melons. It grows on a climbing plant that is 3 to 10 feet long; the plant’s tendrils allow it to cling to other plants or objects. The fruit emerges after the plant’s large yellow flowers have blossomed. Characterized by a straight, plump shape with slightly tapered ends and smooth skin with an even dark green color', 'Cucumbers will grow quickly with little care. Be sure they receive an inch of water every week. Make the most of your food growing efforts by regularly feeding plants with a water-soluble plant food. When soil is warm, add a layer of straw mulch to keep fruit clean and help keep slugs and beetles away.');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_image_1, plant_image_2, plant_image_3, plant_zone, water_level, light_level,difficulty_level, plant_description, plant_care) VALUES ('Butternut Squash', 'Cucurbita moschata','Vegetable','https://res.cloudinary.com/dwdijh29x/image/upload/v1733239999/butternut-squash_rsmgjq_ebt2y1.webp', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241108/butternut_d8fldf_yjwzkf.webp', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241101/how-to-grow-winter-squash_hdkavk_dkudfm.jpg', '3-11', '1', '3','3','Butternut squash is known in Australia and New Zealand as butternut pumpkin or gramma, is a type of winter squash that grows on a vine. It has a sweet, nutty taste similar to that of a pumpkin. It has tan-yellow skin and orange fleshy pulp with a compartment of seeds in the blossom end.', 'All squash plants are grown in the same way, requiring a lot of space and nutrients. Set aside a generous portion of your plot to grow them in and add plenty of organic matter, such as homemade compost or well-rotted manure. This will provide them with sufficient nutrients to see them through their long growing season.');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level,difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Broccoli', 'Brassica oleracea var. italica', 'Vegetable','3-10','1-2 inches','3','3','https://res.cloudinary.com/dwdijh29x/image/upload/v1733239998/broc_ayv6re_bnj45n.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942649/broccoli2_ybus3p_n3tvaq.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942650/brocolli3_ihir39_ist7fu.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level,difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Potato', 'Solanum tuberosum', 'Vegetable','3-10','1-2','2','2', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239988/potatoes_kaphgl_vif44c.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942683/potato2_oawhd6_wdsrsh.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942685/potato3_vqypmt_crrknl.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level,difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Onion','Allium cepa', 'Vegetable','3-9','1','3','2', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239986/onions_r6xoax_qdkgqs.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733944705/onion2_bluge9_ol5kyy.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733944708/onion3_e1oxl7_oq1xlc.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level,difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Okra', 'Abelmoschus esculentus', 'Vegetable','5-11','1-2','3','2', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239985/okra_w9z2tx_zgxfoo.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942672/okra2_kqrjkw_uvhe2h.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942674/okra3_gj3btt_ymp3pr.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level,difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Turnip', 'Brassica rapa subsp. rapa','Vegetable','3-10','1','3','1', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239992/turnips_nwnj2v_jdicnp.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942697/turnip2_hdyrtq_llr7pw.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942699/turnip3_kpv2t5_rw5cab.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level,difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Carrot', 'Daucus carota subsp. sativus', 'Vegetable','3-10','1','3','1', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733240000/carrots_fzqzxq_hykrze.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942655/carrot2_juoqbz_zbcldq.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942657/carrot3_mu9lni_axxhzr.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level,difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Bell Pepper', 'Capsicum', 'Vegetable','4-11','1-2','3','3','https://res.cloudinary.com/dwdijh29x/image/upload/v1733239995/bellpeppers_hjzrya_bthf8y.webp','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942643/bellpepper2_idgxdc_uo99gd.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942644/bellpepper3_pxl5dx_ticagj.jpg');


INSERT INTO plants (plant_name, scientific_name, plant_type, plant_image_1, plant_image_2, plant_image_3, plant_zone, water_level, light_level,difficulty_level, plant_description, plant_care)  VALUES ('Basil', 'Ocimum basilicum', 'Herb', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239995/Basil_j5v4uu_dbstit.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241106/basil2_bkbamw_sbioci.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241107/Basil3_mhjfz4_k5utte.jpg', '4-10','1','3','1', 'Pungent basil leaves fresh from the summer herb garden offer aroma and taste in a myriad of dishes. Normally thought of as Italian or Mediterranean, basil originated in Africa and southern Asia—India, Thailand, and Vietnam. Among the many different varieties and flavors, there is a slight difference in levels of essential oils. Numerous varieties are easy to grow in pots or in the ground.', 'Basil is quite sensitive to cold and is best grown in hot, summer sun. Germination depends on warm soil and air above 75 degrees. Basil seed can be sown indoors or in a greenhouse in May and planted out in June in Sonoma County after days are warm. Plant-to-harvest is about 10 weeks. Basil cuttings may be rooted in a glass of water and then transplanted into pots or the garden. Basil should be grown in well-drained soil enriched with compost in full sun. Frequent harvesting of the outer leaves prolongs life of the plant and makes it bushier.');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_image_1, plant_image_2, plant_image_3, plant_zone, water_level, light_level,difficulty_level, plant_description, plant_care)  VALUES ('Cilantro', 'Coriandrum sativum', 'Herb', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733240005/Cilantro_c2mzkj_nsqjkg.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241110/Cilantro2_kcz9p5_r2gxba.webp', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241110/cilantro_cu6trq_nddddz.png', '2-11', '1','2','2', 'Coriandrum sativum is a tender annual herb whose fresh leaves are known as cilantro and dried seeds are known as coriander. Every part of the plant is edible and especially useful in East Indian, Asian, Mediterranean, and Latin cuisines.', 'Cilantro plants require a little more tending than most herbs to sustain them through their naturally short growing season. Cilantro is neither frost- nor heat-tolerant in Sonoma County and must be grown from about May 1 to mid-November. Cilantro depends on moist soil to develop robust plants. Irregular watering causes plants to bolt before they produce ample leaves and mature. Small crops thrive when sown in containers and may be easier to tend than in beds.');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_image_1, plant_image_2, plant_image_3, plant_zone, water_level, light_level,difficulty_level, plant_description, plant_care)  VALUES ('Dill', 'Anethum graveolens', 'Herb', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733240006/Dill_biszrw_j0fqzl.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733240006/Dill_biszrw_j0fqzl.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241095/dill_yvzatq_hb3and.jpg', '2-11','1','3','1', 'Graceful in the garden, dill plants attract beneficial insects to their flat-headed, yellow flowers and offer both seeds and leaves, called dill weed, when dried. Although not difficult to grow, dill is a bit more challenging to sustain than some other herbs as it requires flower removal and repeated sowing.', 'Dill prefers nice warm weather, and is super easy to grow.  It is extremely drought tolerant, as it has a pretty long tap root.  If you are not growing dill in groupings, you may need to provide a bit of support so it doesn’t topple over. Dill is an excellent companion crop for certain asparagus varieties, onions, and members of the Brassica family (cabbage, broccoli, kale, etc.), and cucumbers.');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Chives', 'Allium schoenoprasum', 'Herb','3-9','1','2','1', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733240004/chives_xc4961_lcqclw.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942658/chives2_thgjmx_mkavne.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942660/chives3_cy319x_ys4gai.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Parsley', 'Petroselinum crispum', 'Herb','2-11','1','2','1','https://res.cloudinary.com/dwdijh29x/image/upload/v1733239987/parsley_wy9tso_skcjc2.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942680/parsley2_xkunyh_ob79v1.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942681/parsley3_v4mcnz_yplvrz.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Oregano', 'Origanum vulgare', 'Herb','4-9','1','3','1', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239986/oreganoplant_kclkkw_pz4d4h.webp','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942676/oregano2_nekzc8_z8mi02.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942678/oregano3_je9j54_xtqmgj.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Sage', 'Salvia officinalis', 'Herb','4-8','1','3','2','https://res.cloudinary.com/dwdijh29x/image/upload/v1733239990/sage_mrnyyn_bwvrb3.webp','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942690/sage2_piyp0q_fnngzg.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942692/sage3_corsov_latrxz.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Thyme', 'Thymus vulgaris', 'Herb','5-9','1','3','1', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239991/thyme_qtwn1n_l97jef.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942694/thyme2_bddsqe_va45po.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942696/time3_c5ph7n_exjadr.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Mint', 'Mentha', 'Herb','3-8','2','2','1','https://res.cloudinary.com/dwdijh29x/image/upload/v1733239984/mint_skev2j_ntsn8c.webp','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942669/mint2_ujjr45_tescip.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942671/mint3_kmfzar_ofjlfy.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3) VALUES ('Lemon Balm', 'Melissa officinalis', 'Herb','4-9','1','2','1','https://res.cloudinary.com/dwdijh29x/image/upload/v1733239983/lemonbalm_vc12ac_blrmrn.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942665/lemonbalm2_bvnwu1_dg91s3.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942667/lemonbalm3_svjqnp_ctqxkf.jpg');



INSERT INTO plants (plant_name, scientific_name, plant_type, plant_image_1, plant_image_2, plant_image_3, plant_zone, water_level, light_level, difficulty_level, plant_description, plant_care)  VALUES ('Watermelon','Citrullus lanatus', 'Fruit', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239993/watermelon_lxfxiy_mcmmds.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241104/water1_hkgf6j_grwzri.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241105/water3_gopjsf_o85b4x.jpg', '3-9','2','3','3', 'Watermelon is grown in favorable climates from tropical to temperate regions worldwide for its large edible fruit, which is a berry with a hard rind and no internal divisions, and is botanically called a pepo. The sweet, juicy flesh is usually deep red to pink, with many black seeds, although seedless varieties exist.','Watermelons grow best in sunny locations and in fertile, well-drained soils. Incorporate organic matter and a complete fertilizer into the area before planting. Plant 4-6 watermelon seeds directly in the garden when soils are 65°F. Seeds should be planted 1-2 inches deep, in mounds 4 feet apart. Thin the mounds after emergence to two plants. Transplant watermelon 2 feet apart through black plastic for early maturity. Use row covers or hot caps to protect the plants when planting before the frost-free period.');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_image_1, plant_image_2, plant_image_3, plant_zone, water_level, light_level, difficulty_level, plant_description, plant_care)  VALUES ('Strawberry', 'Fragaria × ananassa', 'Fruit', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239990/strawberry_ysoaao_wugda3.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241102/strawberry1_cmwaiy_elu5i4.webp', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241103/strawberry2_w6rq6j_vvsoev.jpg', '4-9','1-2','3','2', 'The strawberry plant is in many ways unique. It is an herbaceous perennial, composed of leaves, a crown (a compressed, modified stem), and a root system. In heavier soils such as clay loams, 90 percent of the roots can be located in the top 6 inches of soil. This shallow root system is, in part, responsible for the strawberry plant''s sensitivity to water deficit and excess. Runners, or stolons, arise from buds at the base (axils) of the leaves; they are the strawberry plant''s device for vegetative propagation.', 'Strawberries are among the most widely grown fruit in the home garden. Strawberries prefer a well drained soil, high in organic matter. They need full sun for the highest yields, at least 6 hours per day. Do not plant strawberries where peppers, tomatoes, eggplant and potatoes have been grown. These plants could harbor verticillium wilt, a serious strawberry disease. Strawberries need about one inch of water per week during the growing season.');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_image_1, plant_image_2, plant_image_3, plant_zone, water_level, light_level, difficulty_level, plant_description, plant_care)  VALUES ('Blueberry','Vaccinium sect. Cyanococcus', 'Fruit', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239997/blueberries_hgh8dj_qeg7x3.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241097/do-blueberries_qwm1gj_teks35.jpg', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733241098/Grow-Blueberries_rsv6iz_cvk6jr.jpg', '3-10','2','3','4','Most gardeners plant blueberries to reap the rewards of the delicious fruits, but they are often planted as an ornamental for the benefit of their attractive foliage and shrubby form. Blueberry bushes will grow in nearly any area regardless of the intensity of the sun if adequate cultural methods are adhered to, including soil acidity, sufficient water, and a protective mulch over the root zone.', 'Blueberries require cross-pollination to set fruit. Bees need to visit 2 different varieties planted near each other that bloom at the same time. Blueberries are shallow-rooted and need a protective layer of mulch to hold in soil moisture, guard against temperature extremes, and prevent weed growth. After planting, mulch the entire root area with 6-in. of shredded bark or nitrolized sawdust.');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3)                                  VALUES ('Raspberry', 'Rubus idaeus', 'Fruit','3-9','1-2','3','3', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239989/raspberry_j0f1rf_evuxnb.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942687/raspberry2_faf2rh_bjhc1o.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942688/raspberry3_vth2an_aafplo.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3)                                  VALUES ('Blackberry', 'Rubus subg. Rubus', 'Fruit','5-9','1-2','3','3','https://res.cloudinary.com/dwdijh29x/image/upload/v1733239996/blackberry_xekkwd_saquto.webp','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942646/blackberry2_m7ynxw_cjk543.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942647/blackberry3_rn0opy_r3a8bg.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3)                                  VALUES ('Cantaloupe', 'Cucumis melo var. cantalupensis', 'Fruit','4-11','1-2','3','3', 'https://res.cloudinary.com/dwdijh29x/image/upload/v1733239999/cantaloupe_kyphss_pnwnxz.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942652/cantaloupe2_d8gjpg_bh0moz.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942654/cantaloupe3_pouc04_ulq007.jpg');
INSERT INTO plants (plant_name, scientific_name, plant_type, plant_zone, water_level, light_level, difficulty_level, plant_image_1, plant_image_2, plant_image_3)                                  VALUES ('Figs', 'Ficus carica', 'Fruit','7-10','1','3','4','https://res.cloudinary.com/dwdijh29x/image/upload/v1733239983/fig_sal82s_r2x1v4.avif','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942662/figs2_k5uwfs_qdjpjr.jpg','https://res.cloudinary.com/dxuznyexo/image/upload/v1733942663/figs3_u0c1bm_ujccud.jpg');


INSERT INTO garden (plant_id, user_id) VALUES (1, 1);
INSERT INTO garden (plant_id, user_id) VALUES (2, 1);
INSERT INTO garden (plant_id, user_id) VALUES (3, 1);
INSERT INTO garden (plant_id, user_id) VALUES (4, 1);

COMMIT TRANSACTION;
